# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"
"cargo:cargo-about" = "0.8.4"
"github:rust-cross/cargo-zigbuild" = "0.23.4"
gh = "2.96.0"
helm = "4.1.1"
jq = "1.8.2"
rust = { version = "1.97.1", profile = "minimal", components = [ "clippy", "llvm-tools-preview", "rustfmt" ], targets = [ "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "riscv64gc-unknown-linux-musl" ] }
shellcheck = "0.11.0"
zig = "0.15.2"

[bootstrap.packages]
# APT
"apt:apt-utils" = "latest"
"apt:build-essential" = "latest"
"apt:debsigs" = "latest"
"apt:createrepo-c" = "latest"
"apt:gnupg" = "latest"
"apt:libssl-dev" = "latest"
"apt:perl" = "latest"
"apt:pkg-config" = "latest"
"apt:rpm" = "latest"

# DNF
"dnf:createrepo_c" = "latest"
"dnf:gcc" = "latest"
"dnf:gnupg2" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:perl" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:rpm" = "latest"

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://git.dimidiumlabs.io/platform.git//tasks?ref=d6639bb2f831afedfa0b55faf5869311b04d9d74",
]

[tasks.fmt]
run = "cargo fmt --all --check"

[tasks.clippy]
run = "cargo clippy --all-targets --all-features -- -D warnings"

[tasks.test]
run = """
cargo build --release
cargo test --all-features --release --locked
"""

[tasks.smoke]
run = "cargo run -p smoke"

[tasks.smoke-local]
run = "./tests/smoke/run-local.sh"

[tasks.coverage]
run = """
mkdir -p target/coverage/
cargo llvm-cov --all-features --workspace --lcov --output-path target/coverage/lcov.info
cargo llvm-cov --all-features --workspace --html --output-dir target/coverage/html
"""
