# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v2
type: application

# Replaced by the release task when the chart is packaged.
version: 0.0.0
appVersion: dev

name: tesor
home: https://git.dimidiumlabs.io/tesor
description: Tiny package caching proxy
